import { Language, AppTranslations, AppSettings, AssessmentDimensionSetting, CandidateStatus, JobStatus } from './types';

export const APP_NAME = "RecruitX"; 
export const GEMINI_MODEL_TEXT = 'gemini-2.5-flash-preview-04-17'; // General text tasks
export const PDF_MAX_SIZE_MB = 3; // Max size for PDF files in MB
export const CACHE_EXPIRY_MS = 24 * 60 * 60 * 1000; // 24 hours for cache expiry
export const ANALYSIS_DURATION_ESTIMATE_MS = 22000; // Adjusted estimated duration for analysis, might be longer with more dimensions

export const DEFAULT_LANGUAGE = Language.EN;

export const DEFAULT_ASSESSMENT_DIMENSIONS: AssessmentDimensionSetting[] = [
  {
    id: 'skill_assessment',
    label: 'Skills Assessment',
    promptGuidance: "Evaluate the candidate's technical skills, soft skills, and tool proficiency against the job requirements. Consider both explicitly listed skills and those inferred from project descriptions or experience. Identify key strengths, and any notable gaps or areas where proficiency level is unclear. Score based on the breadth, depth, and relevance of skills. Explain how Recruiter Notes influenced this score.",
    isActive: true,
    isDefault: true,
  },
  {
    id: 'experience_alignment',
    label: 'Experience Alignment',
    promptGuidance: "Assess the candidate's years of experience, the relevance of their past roles, project exposure, and significant achievements in relation to the job description's experience requirements. Consider the seniority, scope, and impact of their previous positions. Score higher for directly relevant experience at appropriate levels of responsibility. Explain how Recruiter Notes influenced this score.",
    isActive: true,
    isDefault: true,
  },
  {
    id: 'professionalism_collaboration',
    label: 'Professionalism & Collaboration Indicators',
    promptGuidance: "From the language, tone, and structure of the CV, and any described team interactions or project roles, evaluate indicators of professionalism, communication style, teamwork aptitude, and collaborative spirit. Note any evidence of adaptability or problem-solving approach in team contexts. Focus on professional conduct. Higher scores for clear evidence of positive collaborative behaviors. Explain how Recruiter Notes influenced this score.",
    isActive: true,
    isDefault: true,
  },
  {
    id: 'problem_solving_complexity',
    label: 'Problem-Solving & Complexity Handling',
    promptGuidance: "Analyze project descriptions and achievements for evidence of the candidate's ability to tackle complex problems, devise innovative solutions, and manage challenging tasks. Look for specific examples of analytical thinking and successful outcomes in complex situations. Score based on the scale and difficulty of problems solved. Explain how Recruiter Notes influenced this score.",
    isActive: true,
    isDefault: true,
  },
  {
    id: 'impact_achievements_quantified',
    label: 'Quantifiable Impact & Achievements',
    promptGuidance: "Identify and evaluate the quantifiable impact of the candidate's achievements in previous roles. Look for metrics, data, or specific results that demonstrate their contributions (e.g., 'increased sales by X%,' 'reduced costs by Y,' 'led a team of Z to deliver project A'). Assess the significance of these achievements. Higher scores for clearly stated, significant, and relevant impacts. Explain how Recruiter Notes influenced this score.",
    isActive: true,
    isDefault: true,
  },
  {
    id: 'learning_agility_adaptability', 
    label: 'Learning Agility & Adaptability',
    promptGuidance: "Assess the CV for indicators of continuous learning, skill development, and adaptability to new technologies, methodologies, or changing environments. Look for diverse project experiences, acquisition of new skills over time, or handling of evolving roles. Score higher for demonstrated proactivity in learning and successful adaptation. Explain how Recruiter Notes influenced this score.",
    isActive: true,
    isDefault: true,
  },
  {
    id: 'leadership_initiative',
    label: 'Leadership & Initiative Potential',
    promptGuidance: "Identify any evidence of leadership qualities, mentorship roles, or proactive initiative taken by the candidate in their projects or roles. This includes formal leadership positions as well as informal influence or leading project components. Score based on the level of responsibility and proactive engagement shown. Explain how Recruiter Notes influenced this score.",
    isActive: true,
    isDefault: true,
  },
  {
    id: 'communication_clarity_cv',
    label: 'Written Communication Clarity (CV)',
    promptGuidance: "Based purely on the CV's structure, language, and clarity of project descriptions, assess the candidate's written communication skills. Is the information presented logically, concisely, and professionally? Is it easy to understand their roles and accomplishments? Score higher for exceptionally clear, well-structured, and impactful CV presentation. Explain how Recruiter Notes influenced this score.",
    isActive: true,
    isDefault: true,
  },
  {
    id: 'key_term_technology_alignment',
    label: 'Key Term & Technology Alignment',
    promptGuidance: "Perform a specific check for the presence and contextual relevance of key technologies, methodologies, or domain-specific terms explicitly mentioned as critical in the Job Description. Note both presence and apparent depth of experience with these terms. Score based on the coverage and relevance of these key terms. Explain how Recruiter Notes influenced this score.",
    isActive: true,
    isDefault: true,
  },
  {
    id: 'holistic_impression_xfactor',
    label: 'Holistic Impression & X-Factor',
    promptGuidance: "Beyond individual criteria, provide a brief holistic impression of the candidate's profile in relation to the job. Note any unique strengths, 'X-factor' qualities (e.g., exceptional passion, unique combination of skills) or potential red flags that emerge from a comprehensive review of the CV against the JD. This score reflects an overall gut feeling based on the complete profile. Explain how Recruiter Notes influenced this score.",
    isActive: true,
    isDefault: true,
  }
];

export const DEFAULT_NEXUS_RANKING_SCORE_THRESHOLD = 0; 

export const DEFAULT_APP_SETTINGS: AppSettings = {
  assessmentDimensions: DEFAULT_ASSESSMENT_DIMENSIONS,
  nexusRankingScoreThreshold: DEFAULT_NEXUS_RANKING_SCORE_THRESHOLD,
};

export const CANDIDATE_STATUS_OPTIONS: {value: CandidateStatus | 'ALL', labelKey: string}[] = [
  { value: 'ALL', labelKey: 'statusAll' },
  { value: 'ACTIVE_SEEKER', labelKey: 'statusCandidateActiveSeeker' },
  { value: 'OPEN_TO_OFFERS', labelKey: 'statusCandidateOpenToOffers' },
  { value: 'PASSIVELY_LOOKING', labelKey: 'statusCandidatePassivelyLooking' },
  { value: 'IN_PROCESS_INTERNAL', labelKey: 'statusCandidateInProcessInternal' },
  { value: 'NOT_LOOKING', labelKey: 'statusCandidateNotLooking' },
  { value: 'ARCHIVED', labelKey: 'statusCandidateArchived' },
];

export const JOB_STATUS_OPTIONS: {value: JobStatus | 'ALL', labelKey: string}[] = [
  { value: 'ALL', labelKey: 'statusAll' },
  { value: 'OPEN_HIRING', labelKey: 'statusJobOpenHiring' },
  { value: 'INTERVIEWING', labelKey: 'statusJobInterviewing' },
  { value: 'OFFER_EXTENDED', labelKey: 'statusJobOfferExtended' },
  { value: 'FILLED', labelKey: 'statusJobFilled' },
  { value: 'ON_HOLD', labelKey: 'statusJobOnHold' },
  { value: 'CLOSED_CANCELLED', labelKey: 'statusJobClosedCancelled' },
];


export const TRANSLATIONS: AppTranslations = {
  [Language.EN]: {
    appName: APP_NAME,
    tagline: "RecruitX: Precision Talent Intelligence.",
    // Old DocumentInput related, some may be reused or removed
    cvInputLabel: "CV Content (Paste or Upload: .txt, .pdf, .docx, .xlsx)",
    jdInputLabel: "Job Description Content (Paste or Upload: .txt, .pdf, .docx, .xlsx)",
    cvNameLabel: "CV / Candidate Identifier",
    jdTitleLabel: "Job Title / Position Identifier",
    matchButton: "Analyze Match", // Will be used in Matching View
    bulkMatchButton: "Bulk Analyze Matches", // Will be used in Matching View
    resetButton: "Clear Sections", // Might be "Clear Selections" in Matching view
    loadingMessage: "Performing Analysis...",
    errorTitle: "Error Occurred",
    reportTitle: "Candidate Match Report",
    overallMatchScore: "Overall Match Score",
    scoreBreakdown: "Score Breakdown",
    detailedAnalysis: "Comprehensive Analysis",
    explanation: "Rationale",
    biasWarning: "Note: This AI analysis is designed to provide objective insights based on textual content. Human oversight and comprehensive evaluation are crucial for final hiring decisions.",
    footerText: `© ${new Date().getFullYear()} RecruitX by Shristyverse LLC. All rights reserved.`,
    selectCV: "Select CV(s) for Analysis", // Used in Matching View
    selectJD: "Select Job Description(s) for Analysis", // Used in Matching View
    // Old addCV/addJD, to be replaced by more generic terms for SimpleDocumentForm
    addCV: "Add CV(s) to System", 
    addJD: "Add JD(s) to System",
    noCVs: "No CVs currently in the system. Add CVs via the 'Candidates' tab.",
    noJDs: "No Job Descriptions currently in the system. Add JDs via the 'Jobs' tab.",
    selectCVAndJD: "Please select one CV and one Job Description for analysis.",
    selectMultipleCvAndJd: "For bulk analysis, please select one or more CVs and one or more Job Descriptions.",
    cv: "CV",
    jd: "Job Description",
    candidate: "Candidate",
    job: "Position",
    matchDetailsFor: "Match Report for",
    and: "and",
    noReport: "Select documents and initiate analysis from the 'Matching' tab to view a report.",
    score: "Score",
    // Placeholders for SimpleDocumentForm
    uploadCVPlaceholder: "Paste CV content or upload a file. Content will appear here if text-based.",
    uploadJDPlaceholder: "Paste Job Description content or upload a file. Content will appear here if text-based.",
    cvNamePlaceholder: "e.g., J. Doe - Senior Analyst",
    jdTitlePlaceholder: "e.g., Lead Data Scientist",
    uploadFile: "Upload File (.txt, .pdf, .docx, .xlsx)", // For SimpleDocumentForm
    recruiterNotesLabel: "Recruiter Notes (Optional)",
    recruiterNotesPlaceholder: "Provide any specific context, critical requirements, or areas of emphasis for this document.",
    fileNameLabel: "Uploaded File:",
    contentEditableLabel: "Editable Content:", // For SimpleDocumentForm
    cvRecruiterNotes: "CV Recruiter Notes",
    jdRecruiterNotes: "JD Recruiter Notes",
    noFileSelected: "No file selected.",
    reportGeneratedInLabel: "Report language: {lang}.",
    appLanguageIsLabel: "Application language: {lang}.",
    considerReanalyzingPrompt: "To view this report in {lang}, please re-initiate the analysis.",
    // Dashboard and Navigation
    dashboardTitle: "Recruitment Analytics Dashboard",
    matchingNav: "Matching", 
    dashboardNav: "Dashboard",
    settingsNav: "Settings",
    overview: "System Overview",
    cvsManaged: "Managed CVs",
    jdsManaged: "Managed JDs",
    analysesPerformed: "Analyses Performed",
    recentAnalyses: "Recent Analyses",
    noRecentAnalyses: "No analyses have been performed. Go to 'Matching' to initiate an analysis.",
    viewReportButton: "View Report",
    deleteButton: "Delete",
    confirmDeleteMessage: "Are you sure you wish to delete this item? This action cannot be reversed.",
    analysisDate: "Analysis Date",
    selectReportToView: "Select an analysis from the dashboard to view detailed report.",
    backToDashboard: "Return to Dashboard",
    startNewAnalysis: "Initiate New Analysis", 
    selectCVsAndJDsForMatching: "Select CVs and Job Descriptions for Matching Analysis", 
    performMatchAnalysisButton: "Perform Match Analysis", 
    performBulkMatchAnalysisButton: "Perform Bulk Match Analysis", 
    clearSelectionsButton: "Clear Selections", 

    filterByDimensionCountLabel: "Filter by Dimensions Used:",
    filterOptionAllReports: "All Reports",
    filterOption1to3Dimensions: "1-3 Dimensions",
    filterOption4to6Dimensions: "4-6 Dimensions",
    filterOption7to10Dimensions: "7-10 Dimensions",
    noAnalysesWithFilter: "No analyses match the current filter criteria.",
    // New Dashboard Filters
    filtersSectionTitle: "Filters",
    filterByScoreThresholdLabel: "Min. Overall Score:",
    filterByDateRangeLabel: "Analysis Date Range:",
    filterStartDateLabel: "Start Date",
    filterEndDateLabel: "End Date",
    clearDateFilterButton: "Clear Dates",
    noAnalysesWithScoreDateFilter: "No analyses match the current score and/or date range filters.",

    // Candidate & Job Management
    candidatesNav: "Candidates",
    jobsNav: "Jobs",
    candidateProfileTitle: "Candidate Profile",
    jobProfileTitle: "Job Profile",
    editCandidateProfileTitle: "Edit Candidate Profile",
    editJobProfileTitle: "Edit Job Profile",
    saveChangesButton: "Save Changes",
    cancelButton: "Cancel",
    replaceFileButton: "Replace File",
    allCandidatesTitle: "All Candidates",
    allJobsTitle: "All Jobs",
    noCandidatesManaged: "No candidates managed. Use 'Add New Candidate' to begin.",
    noJobsManaged: "No jobs managed. Use 'Add New Job' to begin.",
    addDocumentButton: "Add Document", 
    addCandidateButton: "Add New Candidate", 
    addJobButton: "Add New Job", 
    addNewCandidateTitle: "Add New Candidate",
    addNewJobTitle: "Add New Job Profile",
    viewEditProfileButton: "View / Edit Profile",
    contentNonEditable: "Content is non-editable (file-based). You can replace the file.",
    confirmDeleteCandidateMessage: "Are you sure you wish to delete this candidate? All associated analysis reports will also be removed. This action cannot be reversed.",
    confirmDeleteJobMessage: "Are you sure you wish to delete this job? All associated analysis reports will also be removed. This action cannot be reversed.",
    documentStatusLabel: "Status",
    filterByStatusLabel: "Filter by Status:",
    statusAll: "All Statuses",
    statusCandidateActiveSeeker: "Actively Seeking",
    statusCandidateOpenToOffers: "Open to Offers",
    statusCandidatePassivelyLooking: "Passively Looking",
    statusCandidateInProcessInternal: "In Process (RecruitX)",
    statusCandidateNotLooking: "Not Looking",
    statusCandidateArchived: "Archived",
    statusJobOpenHiring: "Open (Actively Hiring)",
    statusJobInterviewing: "Interviewing",
    statusJobOfferExtended: "Offer Extended",
    statusJobFilled: "Filled",
    statusJobOnHold: "On Hold",
    statusJobClosedCancelled: "Closed / Cancelled",
    noCandidatesWithStatusFilter: "No candidates match the current status filter.",
    noJobsWithStatusFilter: "No jobs match the current status filter.",
    errorUnsupportedFileType: "Unsupported file type. Please upload .txt, .pdf, .doc, .docx, .xls, or .xlsx files.",
    errorFileSizeTooLarge: `File size exceeds the ${PDF_MAX_SIZE_MB}MB limit for PDFs.`,
    errorParsingFile: "Error parsing file content. The file may be corrupted or in an unsupported format.",
    processingFile: "Processing file...",
    errorBulkOperation: "Bulk operation completed with {errorCount} error(s). Details:\n{errorMessages}",
    cacheHitMessage: "Analysis retrieved from cache. (Generated: {date})",
    analysisProgressMessage: "AI Analysis Progress: {progress}%",
    currentStageLabel: "Status:",
    stagePreparingEnv: "Initializing analysis environment...",
    stageProcessingCv: "Processing CV data (incl. OCR for PDF)...",
    stageProcessingJd: "Processing Job Description data (incl. OCR for PDF)...",
    stagePrioritizingNotes: "Integrating recruiter insights...",
    stageCrossReferencing: "Skills and experience being cross-referenced...",
    stageCalculatingScores: "Calculating scores and evaluating fit...",
    stageGeneratingReport: "Generating comprehensive report...",
    stageAnalysisComplete: "Analysis Complete.",
    stageAnalysisFailed: "Analysis Failed. Review errors.",
    settingsTitle: "Application Settings",
    assessmentDimensionsSectionTitle: "Assessment Dimensions",
    dimensionProcessingTimeWarning: "Note: Activating more dimensions can increase AI analysis time.",
    addDimensionButton: "Add New Dimension",
    dimensionLabelLabel: "Dimension Label",
    dimensionLabelPlaceholder: "e.g., Leadership Potential, Technical Communication",
    dimensionPromptGuidanceLabel: "AI Prompt Guidance for this Dimension",
    dimensionPromptGuidancePlaceholder: "Instruct the AI on what to look for and how to evaluate this dimension. Be specific.",
    dimensionIsActiveLabel: "Active",
    dimensionIsDefaultLabel: "(Default)",
    confirmDeleteDimensionMessage: "Are you sure you want to delete this custom dimension? Default dimensions cannot be deleted.",
    rankingDisplaySettingsSectionTitle: "Ranking & Display Settings",
    nexusRankingScoreThresholdLabel: "Nexus Ranking Score Threshold (0-100)",
    nexusRankingScoreThresholdDescription: "Minimum overall score for a match to appear in 'Top Candidate Matches' or 'Best Job Fits' lists.",
    saveSettingsButton: "Save All Settings",
    resetSettingsButton: "Reset to Defaults",
    settingsSavedSuccess: "Settings saved successfully.",
    settingsResetSuccess: "Settings have been reset to default values.",
    errorMinDimensions: "At least one assessment dimension must be active.",
    selectAll: "Select All",
    deselectAll: "Deselect All",
    topCandidateMatchesTitle: "Top Candidate Matches",
    bestJobFitsTitle: "Best Job Fits",
    jumpToProfileButton: "View Profile",
    viewFullAnalysisButton: "View Full Analysis",
    nexusScanPendingMessage: "Nexus Scan Pending: Analyze to reveal connections.",
    noMatchesYet: "No matches found for this item yet.",
    noMatchesAboveThresholdMessage: "No matches meet the current score threshold of {threshold}. Adjust in Settings or perform more analyses.",
    keyStrengthsTitle: "Key Strengths",
    areasForClarificationTitle: "Areas for Clarification",
    strategicDiscussionPointsTitle: "Strategic Discussion Points",
    structuredOverviewTitle: "Structured Overview", 
    refreshStructuredViewButton: "Refresh Structured View",
    structuringDocumentMessage: "Generating structured view...", 
    structuredViewDisclaimer: "This is an AI-generated structured representation for quick review and editing of the parsed data. The original uploaded/pasted content is used for the core AI matching analysis.",
    failedToGenerateStructuredViewMessage: "Failed to generate structured view for this document.",
    editButtonLabel: "Edit",
    doneButtonLabel: "Done",
    addNewEntryButtonLabel: "Add New Entry",
    confirmDeleteEntryMessage: "Are you sure you want to delete this entry?",
    noEntriesFound: "No entries found for this section yet.",
    cvSectionPersonalInfo: "Personal Information",
    cvFieldFullName: "Full Name",
    cvFieldAge: "Age",
    cvFieldSexGender: "Sex/Gender",
    cvFieldPhone: "Phone",
    cvFieldAddress: "Address",
    cvFieldEmail: "Email",
    cvFieldLinkedIn: "LinkedIn",
    cvFieldPortfolio: "Portfolio",
    cvSectionSummary: "Summary / Objective",
    cvSectionWorkExperience: "Work Experience",
    cvFieldJobTitle: "Job Title",
    cvFieldCompany: "Company",
    cvFieldDates: "Dates",
    cvFieldDescription: "Description",
    cvFieldResponsibilities: "Responsibilities",
    cvFieldAchievements: "Achievements",
    cvSectionEducation: "Education",
    cvFieldDegree: "Degree",
    cvFieldInstitution: "Institution",
    cvFieldGraduationDate: "Graduation Date",
    cvFieldEduDetails: "Details",
    cvSectionSkills: "Skills",
    cvFieldSkillCategory: "Category",
    cvFieldSkillsList: "Skills",
    cvSectionProjects: "Projects",
    cvFieldProjectName: "Project Name",
    cvFieldProjectDescription: "Description",
    cvFieldTechnologiesUsed: "Technologies Used",
    cvFieldProjectRole: "Role",
    cvFieldProjectDates: "Dates",
    cvSectionCertifications: "Certifications",
    cvSectionAwards: "Awards & Recognitions",
    cvSectionLanguages: "Languages",
    jdFieldJobTitle: "Job Title",
    jdSectionCompanyOverview: "Company Overview",
    jdSectionRoleSummary: "Role Summary / Purpose",
    jdSectionKeyResponsibilities: "Key Responsibilities",
    jdSectionRequiredQualifications: "Required Qualifications",
    jdSectionPreferredQualifications: "Preferred Qualifications",
    jdSectionTechnicalSkills: "Technical Skills",
    jdSectionSoftSkills: "Soft Skills",
    jdSectionBenefits: "Benefits & Compensation",
    jdSectionLocation: "Location",
    jdSectionSalary: "Salary Range",
    jdSectionOther: "Other Information",
    // Simple Document Form specific
    documentNameLabel: "Document Name / Identifier",
    documentTitleLabel: "Document Title / Identifier",
    documentNamePlaceholder: "e.g., John Doe Resume, Senior Dev Role",
    documentTitlePlaceholder: "e.g., Jane Smith - Profile, Lead Engineer JD",
    pasteOrUploadLabel: "Paste CV Content",
    uploadButtonLabel: "Upload File",
    contentPlaceholder: "Paste document content here...",
    notesPlaceholder: "Recruiter Notes (Optional)",
    documentAddedSuccess: "{docType} '{name}' added successfully.",
    genericSaveError: "An error occurred while saving the document.",
    isStructuringMessage: "AI processing document structure...",
    // Bulk Upload
    bulkUploadCvsButton: "Bulk Upload CVs",
    bulkUploadJobsButton: "Bulk Upload Jobs",
    bulkUploadModalTitle: "Bulk Upload {docTypePlural}", // Kept for potential future use, but modal removed
    selectFilesToUploadLabel: "Select Files to Upload (.txt, .pdf, .docx, .xlsx)", // Kept for potential future use
    batchRecruiterNotesLabel: "Batch Recruiter Notes (Optional)", // Kept for potential future use
    batchRecruiterNotesPlaceholder: "These notes will be applied to ALL documents in this batch.", // Kept for potential future use
    startBulkUploadButton: "Start Upload ({fileCount})", // Kept for potential future use
    filesProcessingLabel: "Files processing:",
    fileStatusPending: "Pending", // Not directly used with new inline approach, but kept for completeness
    fileStatusExtracting: "Extracting...", // Not directly used, but kept
    fileStatusUploading: "Adding to system...", // Not directly used, but kept
    fileStatusStructuring: "AI Structuring...", // Not directly used, but kept
    fileStatusProcessing: "Processing", // New general status
    fileStatusSuccess: "Success",
    fileStatusError: "Error",
    bulkUploadSummary: "Upload complete: {successCount} succeeded, {errorCount} failed.",
    closeButton: "Close",
    noFilesSelectedForBulkUpload: "No files selected for bulk upload.",
    searchButton: "Search",
    // AI Methodology Section
    aiMethodologySectionTitle: "Understanding Your RecruitX Analysis",
    aiMethodologyIntro: "RecruitX's AI operates on principles of evidence-based analysis, transparency, and fairness. It meticulously examines the textual content of CVs and Job Descriptions, guided by your Recruiter Notes and defined Assessment Dimensions. The goal is to provide objective, insightful decision support, augmenting human expertise in recruitment.",
    aiMethodologyPointEvidenceTitle: "Evidence-Based Analysis",
    aiMethodologyPointEvidenceDetail: "Scores are derived directly from the text. The AI identifies patterns, keywords, and contextual alignment between the candidate's profile and the job requirements. It highlights specific evidence (or lack thereof) for its conclusions.",
    aiMethodologyPointNotesTitle: "Prioritization of Recruiter Insights",
    aiMethodologyPointNotesDetail: "Your custom notes for CVs and JDs are given high priority. This ensures the AI focuses on what matters most to you for each specific role and candidate, making the analysis highly relevant.",
    aiMethodologyPointFairnessTitle: "Objectivity & Bias Mitigation",
    aiMethodologyPointFairnessDetail: "The AI is designed for objectivity, focusing on skills, experience, and qualifications. It avoids making assumptions based on protected characteristics or information not directly relevant to the job.",
    aiMethodologyPointStructuredTitle: "Structured, Multi-Dimensional Evaluation",
    aiMethodologyPointStructuredDetail: "RecruitX uses a systematic, multi-dimensional approach. Our conceptual multi-agent framework breaks down the complex matching task into specific, evaluable criteria for a thorough and consistent assessment.",
    aiMethodologyPointHumanExpertiseTitle: "AI as a Decision-Support Tool",
    aiMethodologyPointHumanExpertiseDetail: "This AI report is a powerful tool to enhance your decision-making with data-driven insights. It is designed to complement, not replace, your professional judgment and comprehensive evaluation.",
    // AI Assistant View
    aiAssistantNav: "AI Assistant",
    aiAssistantTitle: "AI Recruitment Assistant",
    selectCvLabel: "Select Candidate CV",
    selectJdLabel: "Select Job Description",
    selectCvPlaceholder: "-- Select CV --",
    selectJdPlaceholder: "-- Select JD --",
    analysisResultsTitle: "Analysis Results",
    matchScoreLabel: "Match Score",
    strengthsLabel: "Strengths",
    areasForImprovementLabel: "Areas for Improvement",
    suggestedQuestionsLabel: "Suggested Questions",
    askMeAboutPrompt: "Ask me about candidate evaluation or interview questions",
    messageSenderYou: "You",
    messageSenderAI: "RecruitX AI",
    messagePlaceholder: "Type your question here...",
    processingAgentRequest: "Processing...",
    sendButton: "Send",
    untitledDocument: "Untitled Document",
    candidateNotFound: "Candidate not found.",
    jobNotFound: "Job not found.",
    returnToList: "Return to list",
    errorLoadingData: "Could not load saved data. Your data might be corrupted.",
    candidateIdentifierEmpty: "Candidate identifier cannot be empty.",
    jobTitleEmpty: "Job title cannot be empty.",
    originalFileInfoText: "Original file: {fileName} ({fileMimeType}).",
    pastedTextContent: "Pasted text content.",
    selectedCvOrJdNotFound: "Selected CV or JD not found.",
    analysisDidNotProduceResult: "Analysis did not produce a result.",
    unexpectedErrorDuringAnalysis: "An unexpected error occurred during analysis.",
    noValidCvsOrJdsForBulk: "No valid CVs or JDs selected for bulk analysis.",
    bulkAnalysisComplete: "Bulk analysis complete. {count} report(s) generated. ",
    bulkAnalysisErrors: "{count} error(s) occurred.",
    bulkAnalysisProcessed: "Bulk analysis processed.",
    unexpectedErrorDuringBulkAnalysis: "An unexpected error occurred during bulk analysis.",
    pleaseSelectAtLeastOneCV: "Please select at least one CV.",
    pleaseSelectAtLeastOneJD: "Please select at least one Job Description.",
  },
  [Language.JA]: {
    appName: "リクルートX", 
    tagline: "RecruitX：精密な人材インテリジェンス。",
    cvInputLabel: "履歴書内容 (貼付またはアップロード: .txt, .pdf, .docx, .xlsx)", 
    jdInputLabel: "職務記述書内容 (貼付またはアップロード: .txt, .pdf, .docx, .xlsx)", 
    cvNameLabel: "履歴書/候補者識別子", 
    jdTitleLabel: "職名/ポジション識別子", 
    matchButton: "適合分析を実行", 
    bulkMatchButton: "一括適合分析を実行", 
    resetButton: "選択をクリア", 
    loadingMessage: "分析を実行中...",
    errorTitle: "エラー発生",
    reportTitle: "候補者適合レポート",
    overallMatchScore: "総合適合スコア",
    scoreBreakdown: "スコア内訳",
    detailedAnalysis: "総合分析",
    explanation: "論理的根拠",
    biasWarning: "注：このAI分析は、テキスト内容に基づいた客観的な洞察を提供することを目的としています。最終的な採用決定には、人的な監督と包括的な評価が不可欠です。",
    footerText: `© ${new Date().getFullYear()} RecruitX by Shristyverse LLC. 無断複写・転載を禁じます。`,
    selectCV: "分析対象の履歴書を選択", 
    selectJD: "分析対象の職務記述書を選択", 
    addCV: "履歴書をシステムに追加", 
    addJD: "職務記述書をシステムに追加", 
    noCVs: "現在システムに履歴書がありません。「候補者一覧」タブで追加してください。",
    noJDs: "現在システムに職務記述書がありません。「求人一覧」タブで追加してください。",
    selectCVAndJD: "分析には、履歴書と職務記述書をそれぞれ1つ選択してください。",
    selectMultipleCvAndJd: "一括分析には、1つ以上の履歴書と1つ以上の職務記述書を選択してください。",
    cv: "履歴書",
    jd: "職務記述書",
    candidate: "候補者",
    job: "ポジション",
    matchDetailsFor: "適合レポート対象：",
    and: "及び",
    noReport: "「マッチング」タブで文書を選択し、分析を実行してレポートを表示してください。",
    score: "スコア",
    uploadCVPlaceholder: "履歴書の内容を貼り付けるか、ファイルをアップロードしてください。テキストベースの場合、内容がここに表示されます。", 
    uploadJDPlaceholder: "職務記述書の内容を貼り付けるか、ファイルをアップロードしてください。テキストベースの場合、内容がここに表示されます。", 
    cvNamePlaceholder: "例：山田太郎 - シニアアナリスト", 
    jdTitlePlaceholder: "例：リードデータサイエンティスト", 
    uploadFile: "ファイルアップロード (.txt, .pdf, .docx, .xlsx)", 
    recruiterNotesLabel: "採用担当者メモ (背景情報 - AIが優先考慮)",
    recruiterNotesPlaceholder: "この文書に関する特記事項（AI評価時に重視すべき点など）を入力してください。", 
    fileNameLabel: "アップロードファイル:",
    contentEditableLabel: "編集可能な内容:", 
    cvRecruiterNotes: "履歴書 採用担当者メモ",
    jdRecruiterNotes: "職務記述書 採用担当者メモ",
    noFileSelected: "ファイルが選択されていません。",
    reportGeneratedInLabel: "レポート言語: {lang}。",
    appLanguageIsLabel: "アプリケーション言語: {lang}。",
    considerReanalyzingPrompt: "このレポートを{lang}で表示するには、再度分析を実行してください。",
    dashboardTitle: "採用分析ダッシュボード",
    matchingNav: "マッチング分析", 
    dashboardNav: "ダッシュボード",
    settingsNav: "設定",
    overview: "システム概要",
    cvsManaged: "管理中の履歴書",
    jdsManaged: "管理中の職務記述書",
    analysesPerformed: "実行済み分析数",
    recentAnalyses: "最近の分析",
    noRecentAnalyses: "まだ分析は実行されていません。「マッチング分析」を開始して結果を表示してください。",
    viewReportButton: "レポート表示",
    deleteButton: "削除",
    confirmDeleteMessage: "この項目を削除してもよろしいですか？この操作は元に戻せません。",
    analysisDate: "分析日",
    selectReportToView: "ダッシュボードから分析を選択して詳細レポートを表示してください。",
    backToDashboard: "ダッシュボードへ戻る",
    startNewAnalysis: "新規分析を開始", 
    selectCVsAndJDsForMatching: "マッチング分析のため履歴書と職務記述書を選択",
    performMatchAnalysisButton: "適合分析を実行",
    performBulkMatchAnalysisButton: "一括適合分析を実行",
    clearSelectionsButton: "選択をクリア",

    filterByDimensionCountLabel: "使用ディメンション数でフィルタ:",
    filterOptionAllReports: "すべてのレポート",
    filterOption1to3Dimensions: "1-3 ディメンション",
    filterOption4to6Dimensions: "4-6 ディメンション",
    filterOption7to10Dimensions: "7-10 ディメンション",
    noAnalysesWithFilter: "現在のフィルター条件に一致する分析はありません。",

    // New Dashboard Filters
    filtersSectionTitle: "フィルター",
    filterByScoreThresholdLabel: "最低総合スコア:",
    filterByDateRangeLabel: "分析日範囲:",
    filterStartDateLabel: "開始日",
    filterEndDateLabel: "終了日",
    clearDateFilterButton: "日付をクリア",
    noAnalysesWithScoreDateFilter: "現在のスコアおよび/または日付範囲フィルターに一致する分析はありません。",

    candidatesNav: "候補者一覧",
    jobsNav: "求人一覧",
    candidateProfileTitle: "候補者プロフィール",
    jobProfileTitle: "求人プロフィール",
    editCandidateProfileTitle: "候補者プロフィールの編集",
    editJobProfileTitle: "求人プロフィールの編集",
    saveChangesButton: "変更を保存",
    cancelButton: "キャンセル",
    replaceFileButton: "ファイルを置換",
    allCandidatesTitle: "全候補者",
    allJobsTitle: "全求人",
    noCandidatesManaged: "管理中の候補者はいません。「新規候補者を追加」して開始してください。",
    noJobsManaged: "管理中の求人はいません。「新規求人を追加」して開始してください。",
    addDocumentButton: "文書を追加", 
    addCandidateButton: "新規候補者を追加", 
    addJobButton: "新規求人を追加", 
    addNewCandidateTitle: "新規候補者を追加",
    addNewJobTitle: "新規求人プロファイルの追加",
    viewEditProfileButton: "プロフィール表示/編集",
    contentNonEditable: "内容は編集できません（ファイル形式）。ファイルを置き換えることは可能です。",
    confirmDeleteCandidateMessage: "この候補者を削除してもよろしいですか？関連するすべての分析レポートも削除されます。この操作は元に戻せません。",
    confirmDeleteJobMessage: "この求人を削除してもよろしいですか？関連するすべての分析レポートも削除されます。この操作は元に戻せません。",
    documentStatusLabel: "ステータス",
    filterByStatusLabel: "ステータスで絞り込み:",
    statusAll: "すべてのステータス",
    statusCandidateActiveSeeker: "積極的求職中",
    statusCandidateOpenToOffers: "オファー受付中",
    statusCandidatePassivelyLooking: "消極的求職中",
    statusCandidateInProcessInternal: "選考中 (RecruitX)",
    statusCandidateNotLooking: "求職活動停止中",
    statusCandidateArchived: "アーカイブ済み",
    statusJobOpenHiring: "募集中 (積極採用)",
    statusJobInterviewing: "選考中",
    statusJobOfferExtended: "オファー提示済み",
    statusJobFilled: "採用済み",
    statusJobOnHold: "保留中",
    statusJobClosedCancelled: "募集終了/キャンセル",
    noCandidatesWithStatusFilter: "現在のステータスフィルターに一致する候補者はいません。",
    noJobsWithStatusFilter: "現在のステータスフィルターに一致する求人はいません。",
    errorUnsupportedFileType: "サポートされていないファイル形式です。.txt, .pdf, .doc, .docx, .xls, .xlsxファイルをアップロードしてください。",
    errorFileSizeTooLarge: `ファイルサイズがPDFの${PDF_MAX_SIZE_MB}MB制限を超えています。`,
    errorParsingFile: "ファイル内容の解析中にエラーが発生しました。ファイルが破損しているか、サポートされていない形式の可能性があります。",
    processingFile: "ファイルを処理中...",
    errorBulkOperation: "一括処理中に{errorCount}件のエラーが発生しました。詳細:\n{errorMessages}",
    cacheHitMessage: "分析結果をキャッシュから取得しました。(生成日: {date})",
    analysisProgressMessage: "AI分析進捗: {progress}%",
    currentStageLabel: "ステータス:",
    stagePreparingEnv: "分析環境を初期化中...",
    stageProcessingCv: "履歴書データを処理中 (PDFの場合OCR含む)...",
    stageProcessingJd: "職務記述書データを処理中 (PDFの場合OCR含む)...",
    stagePrioritizingNotes: "採用担当者の洞察を統合中...",
    stageCrossReferencing: "スキルと経験を照合中...",
    stageCalculatingScores: "スコアを計算し、適合性を評価中...",
    stageGeneratingReport: "包括的レポートを生成中...",
    stageAnalysisComplete: "分析完了。",
    stageAnalysisFailed: "分析失敗。エラーを確認してください。",
    settingsTitle: "アプリケーション設定",
    assessmentDimensionsSectionTitle: "評価ディメンション",
    dimensionProcessingTimeWarning: "注：より多くのディメンションを有効にすると、AI分析時間が増加する可能性があります。",
    addDimensionButton: "新しいディメンションを追加",
    dimensionLabelLabel: "ディメンションラベル",
    dimensionLabelPlaceholder: "例：リーダーシップの可能性、技術的コミュニケーション能力",
    dimensionPromptGuidanceLabel: "このディメンションに対するAIプロンプトガイダンス",
    dimensionPromptGuidancePlaceholder: "AIにこのディメンションを評価する方法を具体的に指示してください。",
    dimensionIsActiveLabel: "有効",
    dimensionIsDefaultLabel: "(デフォルト)",
    confirmDeleteDimensionMessage: "このカスタムディメンションを削除してもよろしいですか？デフォルトのディメンションは削除できません。",
    rankingDisplaySettingsSectionTitle: "ランキング・表示設定",
    nexusRankingScoreThresholdLabel: "ネクサスランキングスコア閾値 (0-100)",
    nexusRankingScoreThresholdDescription: "「トップ候補者マッチ」または「ベスト求人フィット」リストに表示されるための最小総合スコア。",
    saveSettingsButton: "すべての設定を保存",
    resetSettingsButton: "デフォルトにリセット",
    settingsSavedSuccess: "設定が正常に保存されました。",
    settingsResetSuccess: "設定がデフォルト値にリセットされました。",
    errorMinDimensions: "少なくとも1つの評価ディメンションを有効にする必要があります。",
    selectAll: "すべて選択",
    deselectAll: "選択解除",
    topCandidateMatchesTitle: "トップ候補者マッチ",
    bestJobFitsTitle: "ベスト求人フィット",
    jumpToProfileButton: "プロフィール表示",
    viewFullAnalysisButton: "完全分析表示",
    nexusScanPendingMessage: "ネクサススキャン保留中：分析して接続を明らかにします。",
    noMatchesYet: "このアイテムに一致するものはまだ見つかりません。",
    noMatchesAboveThresholdMessage: "現在のスコア閾値 {threshold} を満たすマッチはありません。設定で調整するか、さらに分析を実行してください。",
    keyStrengthsTitle: "主な強み",
    areasForClarificationTitle: "要確認事項",
    strategicDiscussionPointsTitle: "戦略的討議ポイント",
    structuredOverviewTitle: "構造化概要", 
    refreshStructuredViewButton: "構造化ビューを更新",
    structuringDocumentMessage: "構造化ビューを生成中...", 
    structuredViewDisclaimer: "これはレビュー用のAI生成構造化表現であり、解析されたデータの編集も可能です。コアAIマッチング分析には、元々アップロード/ペーストされた内容が使用されます。",
    failedToGenerateStructuredViewMessage: "このドキュメントの構造化ビューの生成に失敗しました。",
    editButtonLabel: "編集",
    doneButtonLabel: "完了",
    addNewEntryButtonLabel: "新規項目追加",
    confirmDeleteEntryMessage: "この項目を削除してもよろしいですか？",
    noEntriesFound: "このセクションにはまだエントリがありません。",
    cvSectionPersonalInfo: "個人情報",
    cvFieldFullName: "氏名",
    cvFieldAge: "年齢",
    cvFieldSexGender: "性別",
    cvFieldPhone: "電話番号",
    cvFieldAddress: "住所",
    cvFieldEmail: "メールアドレス",
    cvFieldLinkedIn: "LinkedIn",
    cvFieldPortfolio: "ポートフォリオ",
    cvSectionSummary: "概要・職務要約",
    cvSectionWorkExperience: "職務経歴",
    cvFieldJobTitle: "役職",
    cvFieldCompany: "会社名",
    cvFieldDates: "期間",
    cvFieldDescription: "業務内容",
    cvFieldResponsibilities: "担当業務",
    cvFieldAchievements: "実績",
    cvSectionEducation: "学歴",
    cvFieldDegree: "学位",
    cvFieldInstitution: "教育機関",
    cvFieldGraduationDate: "卒業年月日",
    cvFieldEduDetails: "詳細",
    cvSectionSkills: "スキル",
    cvFieldSkillCategory: "カテゴリ",
    cvFieldSkillsList: "スキル一覧",
    cvSectionProjects: "プロジェクト",
    cvFieldProjectName: "プロジェクト名",
    cvFieldProjectDescription: "内容",
    cvFieldTechnologiesUsed: "使用技術",
    cvFieldProjectRole: "役割",
    cvFieldProjectDates: "期間",
    cvSectionCertifications: "資格",
    cvSectionAwards: "受賞歴・表彰",
    cvSectionLanguages: "語学",
    jdFieldJobTitle: "職務名", 
    jdSectionCompanyOverview: "会社概要",
    jdSectionRoleSummary: "役割概要・職務目的",
    jdSectionKeyResponsibilities: "主な職責",
    jdSectionRequiredQualifications: "必須資格・スキル",
    jdSectionPreferredQualifications: "歓迎資格・スキル",
    jdSectionTechnicalSkills: "技術スキル",
    jdSectionSoftSkills: "ソフトスキル",
    jdSectionBenefits: "福利厚生・報酬",
    jdSectionLocation: "勤務地",
    jdSectionSalary: "給与範囲",
    jdSectionOther: "その他情報",
    // Simple Document Form specific
    documentNameLabel: "文書名/識別子",
    documentTitleLabel: "文書タイトル/識別子",
    documentNamePlaceholder: "例：山田太郎 履歴書、シニア開発職",
    documentTitlePlaceholder: "例：鈴木花子 プロフィール、リードエンジニア職務記述書",
    pasteOrUploadLabel: "履歴書の内容を貼り付け",
    uploadButtonLabel: "ファイルをアップロード",
    contentPlaceholder: "ここに文書の内容を貼り付けてください...",
    notesPlaceholder: "Recruiter Notes (Optional)",
    documentAddedSuccess: "{docType}「{name}」を正常に追加しました。",
    genericSaveError: "文書の保存中にエラーが発生しました。",
    isStructuringMessage: "AIが文書構造を処理中...",
     // Bulk Upload
    bulkUploadCvsButton: "履歴書一括アップロード",
    bulkUploadJobsButton: "求人票一括アップロード",
    bulkUploadModalTitle: "{docTypePlural}一括アップロード",
    selectFilesToUploadLabel: "アップロードするファイルを選択 (.txt, .pdf, .docx, .xlsx)",
    batchRecruiterNotesLabel: "一括採用担当者メモ (任意)",
    batchRecruiterNotesPlaceholder: "これらのメモはこのバッチ内のすべての文書に適用されます。",
    startBulkUploadButton: "アップロード開始 ({fileCount}件)",
    filesProcessingLabel: "ファイル処理中:",
    fileStatusPending: "保留中",
    fileStatusExtracting: "内容抽出中...",
    fileStatusUploading: "システムへ追加中...",
    fileStatusStructuring: "AI構造化処理中...",
    fileStatusProcessing: "処理中",
    fileStatusSuccess: "成功",
    fileStatusError: "エラー",
    bulkUploadSummary: "アップロード完了: {successCount}件成功、{errorCount}件失敗。",
    closeButton: "閉じる",
    noFilesSelectedForBulkUpload: "一括アップロードするファイルが選択されていません。",
    searchButton: "検索",
    // AI Methodology Section
    aiMethodologySectionTitle: "RecruitX分析について",
    aiMethodologyIntro: "RecruitXのAIは、証拠に基づく分析、透明性、公平性の原則に基づいて動作します。履歴書と職務記述書のテキスト内容を綿密に調査し、採用担当者のメモと定義された評価ディメンションに導かれます。目標は、客観的で洞察に満ちた意思決定支援を提供し、採用における人間の専門知識を強化することです。",
    aiMethodologyPointEvidenceTitle: "証拠に基づく分析",
    aiMethodologyPointEvidenceDetail: "スコアはテキストから直接導き出されます。AIは、候補者のプロフィールと職務要件との間のパターン、キーワード、文脈上の整合性を識別します。結論に至った具体的な証拠（またはその欠如）を強調します。",
    aiMethodologyPointNotesTitle: "採用担当者の洞察の優先化",
    aiMethodologyPointNotesDetail: "履歴書や職務記述書に対するカスタムメモは最優先されます。これにより、AIは各特定の役割と候補者にとって最も重要な点に焦点を当て、分析の関連性を高めます。",
    aiMethodologyPointFairnessTitle: "客観性とバイアス軽減",
    aiMethodologyPointFairnessDetail: "AIは客観性を重視し、スキル、経験、資格に焦点を当てるように設計されています。保護されるべき特性や職務に直接関係のない情報に基づいて仮定をすることを避けます。",
    aiMethodologyPointStructuredTitle: "構造化された多次元評価",
    aiMethodologyPointStructuredDetail: "RecruitXは体系的で多次元的なアプローチを使用します。私たちの概念的なマルチエージェントフレームワークは、複雑なマッチング作業を特定の評価可能な基準に分解し、徹底的かつ一貫性のある評価を行います。",
    aiMethodologyPointHumanExpertiseTitle: "意思決定支援ツールとしてのAI",
    aiMethodologyPointHumanExpertiseDetail: "このAIレポートは、データに基づいた洞察により意思決定を強化する強力なツールです。これは、専門的な判断と包括的な評価を補完するものであり、それに取って代わるものではありません。",
    // AI Assistant View
    aiAssistantNav: "AIアシスタント",
    aiAssistantTitle: "AI採用アシスタント",
    selectCvLabel: "候補者の履歴書を選択",
    selectJdLabel: "職務記述書を選択",
    selectCvPlaceholder: "-- 履歴書を選択 --",
    selectJdPlaceholder: "-- 職務記述書を選択 --",
    analysisResultsTitle: "分析結果",
    matchScoreLabel: "マッチスコア",
    strengthsLabel: "強み",
    areasForImprovementLabel: "改善点",
    suggestedQuestionsLabel: "推奨質問",
    askMeAboutPrompt: "候補者評価や面接の質問について聞いてください",
    messageSenderYou: "あなた",
    messageSenderAI: "リクルートX AI",
    messagePlaceholder: "質問を入力してください...",
    processingAgentRequest: "処理中...",
    sendButton: "送信",
    untitledDocument: "無題のドキュメント",
    candidateNotFound: "候補者が見つかりません。",
    jobNotFound: "職務が見つかりません。",
    returnToList: "一覧に戻る",
    errorLoadingData: "保存データの読み込みに失敗しました。データが破損している可能性があります。",
    candidateIdentifierEmpty: "候補者識別子を入力してください。",
    jobTitleEmpty: "職務タイトルを入力してください。",
    originalFileInfoText: "元ファイル: {fileName} ({fileMimeType})。",
    pastedTextContent: "貼り付けたテキスト内容。",
    selectedCvOrJdNotFound: "選択された履歴書または職務記述書が見つかりません。",
    analysisDidNotProduceResult: "分析結果が生成されませんでした。",
    unexpectedErrorDuringAnalysis: "分析中に予期しないエラーが発生しました。",
    noValidCvsOrJdsForBulk: "一括分析用に有効な履歴書または職務記述書が選択されていません。",
    bulkAnalysisComplete: "一括分析完了。{count}件のレポートが生成されました。",
    bulkAnalysisErrors: "{count}件のエラーが発生しました。",
    bulkAnalysisProcessed: "一括分析が処理されました。",
    unexpectedErrorDuringBulkAnalysis: "一括分析中に予期しないエラーが発生しました。",
    pleaseSelectAtLeastOneCV: "少なくとも1つの履歴書を選択してください。",
    pleaseSelectAtLeastOneJD: "少なくとも1つの職務記述書を選択してください。",
  }
};
