name: CI & Observability

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [experiment-service, match-service, report-service, auth-service]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r services/${{ matrix.service }}/requirements.txt
      - name: Run tests
        run: |
          if [ -d services/${{ matrix.service }}/tests ]; then pytest services/${{ matrix.service }}/tests; else echo "No tests for ${{ matrix.service }}"; fi
      - name: Lint code
        run: |
          flake8 . || echo "flake8 not configured"
